### ISSUE TITLE
create annotation by default/make it easier to not use annotation

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#318] opened 2022-06-09 15:26 UTC

**Comment by nicoalee** [comment] 2022-10-04 14:20
duplicate of https://github.com/neurostuff/neurostore/issues/318
duplicate of https://github.com/neurostuff/neurostore/issues/359

**Comment by nicoalee** [comment] 2023-05-18 22:58
resolved as we have created a default "included" annotation

**Closed by nicoalee** 2023-05-18 22:58 UTC
Labels: backend, frontend, medium-effort, medium-impact
